### ISSUE TITLE
Maven Xtend runs Java annotation processor in wrong source directory

### ISSUE THREAD

**Issue by heeckhau** [eclipse/xtext-xtend#1050]
We have a (Eclipse plugin) project with both an annotation processor and Xtend code.
This runs fine in Eclipse, but when we run the build with Maven (Tycho), an unexpected folder appears in the root build folder with a copy of all the generated sources by the annotation processor.

My hypothesis is that Xtend runs the annotation with the wrong "generated sources directory". But maybe the annotation processor does not have to run at all by Xtend?

**Comment by cdietrich** [comment]
i have a Déjà-vu on this, but cannot relate it yet.

**Comment by szarnekow** [comment]
The Xtend Maven Plugin has an "internal" pre-compile step to produce Java class files from a joint compilation of the project sources and Xtend stubs. The precompile does not set any special arguments to the batch compiler.

According to `o.e.j.i.c.batch.Main.configure(String[])`

```
// Enable annotation processing by default in batch mode when compliance is at least 1.6
	// see bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=185768
	if (!didSpecifyDisabledAnnotationProcessing
			&& CompilerOptions.versionToJdkLevel(this.options.get(CompilerOptions.OPTION_Compliance)) >= ClassFileConstants.JDK1_6) {
		this.options.put(CompilerOptions.OPTION_Process_Annotations, CompilerOptions.ENABLED);
	}
```

this implies that annotation processing is enabled for this compile run.
The processors are found by means of a ServiceLoader and will be executed with with the wrong configuration.

This task will:
- pass `DISABLE` by default for the pre-compilation.
- allow to pass compiler args to the pre-compile steps from the maven pom to be able to override its config if desired.
The first change will reduce the likeliness of surprises with the defaults.
The second change will hopefully improve the forward-compatibility since clients will be able to pass their own configuration flags if necessary.
