### ISSUE TITLE
Add support for ternary operator

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#397]
Xtend should support the ternary operator `?:`

- implement grammar, typesystem, compiler
- implement j2x
- evaluate if this can be ported down to xbase https://github.com/eclipse/xtext-extras/issues/244

**Comment by szarnekow** [comment]
We can support this as syntactic sugar for XIfExpression, e.g.

`condition ? doStuff` would be equivalent to `if (condition) doStuff` and `condition ? doStuff: otherwise` is the same as `if (condition) doStuff else otherwise`

In fact, there is no need to change the compiler if we produce the same AST for both variants.

**Comment by szarnekow** [comment]
Mostly because people are often trying ternary operators and get very poor feedback.

**Comment by lievenlemiengre** [comment]
So you could support it in the grammar but flag it as illegal syntax & offer a quickfix? I like that idea :)

**Comment by szarnekow** [comment]
Yes, that would be an option. A configurable validation + quickfix

**Comment by miklossy** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=397793

**Comment by epoell** [comment]
I'll add a validation "Usage of ternary expression" and a quickfix to rewrite it to a "traditional" if-expression. Default severity is ignore.
A quickfix allows to convert it automatically from java-style `val s = (condition) valueA : valueB` to xtend-style `val s = if (condition) valueA else valueB`.

Java2Xtend will be adjusted after that such that it keeps the ternary expression, if the severity is set to ignore. If it is set to error or warning, the ternary will be pasted as if-expression.

**Comment by epoell** [comment]
To be discussed:
Do we want to have a validation, that flags if-expressions on the right-hand-side with a warning, such that we can convert these via quickfix to ternary expressions?
`val s = if (condition) valueA else valueB`  would be flagged, since the if-statement is on the right-hand-side and the validation option is configured to severity error/warning. This could then by quickfix be converted to `val s = (condition) valueA : valueB`.

`{ if (condition) operationA else operationB }` would never be flagged, since it is a statement-like context, not on the right-hand-side of an assignment.

**Comment by miklossy** [comment]
I would rather see the conversion between both styles (ternary expression to traditinal if-expression and traditional if-expression to ternary operation as a [Quick Assist](https://github.com/eclipse/xtext/issues/2379) action instead of a Quickfix action.

What do you think about the idea?

**Comment by szarnekow** [comment]
I like the idea and we did indeed discuss this upfront, too. Unfortunately we do not have the infrastructure available yet to implement quick assists.

**Comment by miklossy** [comment]
Maybe a good opportunity to push the quick assist infrastructure a little bit forward.

**Comment by lievenlemiengre** [comment]
>I would rather see the conversion between both styles (ternary expression to traditinal if-expression and traditional if-expression to ternary operation as a [Quick Assist](https://github.com/eclipse/xtext/issues/2379) action instead of a Quickfix action.

I think the original plan is better (mark as error, offer quick-fix to convert to if-else), I don't think the ternary operator should be part of the xtend language. I still think that having multiple syntactic forms to achieve the same thing is bad language design.

**Comment by szarnekow** [comment]
Thank you @epoell
