### ISSUE TITLE
Add warning for auto cast of a function

### ISSUE THREAD

**Issue by Lexanius** [eclipse/xtext-xtend#476]
Hello team,

The following code

```
if (o instanceof String) {
   return o.length
}
```
 will throw an error in the context of:
```
class Example {

    def foo(Datas it) {
        // not work
        if (o instanceof String) {
            return o.length
        }

       // work
        if (j instanceof String) {
            return j.length
        }
    }

    // works
    def foo(Object o) {
        if (o instanceof String) {
            return o.length
        }
    }
}
```

There is no visible different in `o` and `j` but the Dataobject shows that:

```
    @Data
    static class Datas {

        def Object o() {
            return j
        }

        Object j
    }
```

`o` is a function and the Braces can be leaved out. 

### Problem:

in the eclipse there are only the error that the field not found.

### Solution:

Add warning: "attention you auto-cast a function."

Lexanius

PS: is the right word auto-cast or smart-cast?

**Comment by cdietrich** [comment]
i am not sure if a warning would be correct since its perfectly fine to do a instanceof on the method call (result). (as it is for all expressions) but the autocast wont work and i am not sure of we know the triage of an autocast happens later. @szarnekow am not sure if that is correct but i doubt we can search and find complex expressions to do the auto cast, but i am not sure why we dont do it for simple non field feature calls.

the https://www.eclipse.org/xtend/releasenotes.html use the term auto cast so i think it is the correct one.

**Comment by miklossy** [comment]
See also https://github.com/eclipse/xtext-xtend/issues/435

**Comment by Lexanius** [comment]
> the https://www.eclipse.org/xtend/releasenotes.html use the term auto cast so i think it is the correct one.

Thx

I think it is not usual to make a `instanceof` on a function-call because the function can have side-effects.
The only exception is a `getter `or a `@Pure` method or have u a other example to do this.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
