### ISSUE TITLE
@SupressWarnings("deprecation") not respected

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#637]
A class using deprecated API which is annotated with `SupressWarnings("deprecation")` is still showing deprecation warnings. Take org.eclipse.xtext.xtext.generator.StandardLanguage for example and add the annotation.

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=363685

**Comment by kthoms** [comment]
Then it's a duplicate. Sorry for the noise.

**Comment by tivervac** [comment]
I don't like bugzilla too much so I'll comment here, scold me if I shouldn't.

This bug is a major annoyance of mine and I'd like to have it fixed ASAP. Best way to do that is by doing it myself so that's the way I'll take.

I shortly heard this being mentioned at EclipseCon Europe 2018 so others might have some ideas to share before I start working on this. @szarnekow @kthoms @cdietrich

**Comment by cdietrich** [comment]
i wonder if we could do a incomplete solution just for deprecation.
i am not sure that the correct solution would be. 
(i assume we would need a issueseverityProvider for that, which examines the annotations)
but that only currently looks only at the file and not at the object
the validation for the deprecation already investigates if the declarator is itself deprecated
so we couldk extend that and search for supress deprecation.
