### ISSUE TITLE
compile option to select base library

### ISSUE THREAD

**Issue by shumy** [eclipse/xtext-xtend#64]
This is a ticket from a follow google groups post: https://groups.google.com/forum/#!topic/xtend-lang/OMSN_IKHqbY

Dependent on [#63](https://github.com/eclipse/xtext-xtend/issues/63) resolution.
Add compiler option to select the base library, alternatives to Guava.
[javaslang](http://www.javaslang.io/) looks a nice alternative.

**Comment by chrswk** [comment]
Is there anything that prevents the use of Javaslang in an existing Xtend project? Or are there any features from Javaslang in particular that you fell like are missing in Xtend? Because that would probably be the easier route, since Xtext/Xtend uses Guava all over the place, so the ability to "select a different base library" would require a ridiculous amount of work.

**Comment by cdietrich** [comment]
close as wont fix. feel free to recreate at github.com/eclipse/xtext
