### ISSUE TITLE
Add custom operator sequences

### ISSUE THREAD

**Issue by ivaniesta14** [eclipse/xtext-xtend#676]
Considering Xtend has support for [custom overloaded operators](https://www.eclipse.org/xtend/documentation/203_xtend_expressions.html#operators), the next logical step is to add support for user-made operator sequences.
For example:
```xtend
class Average{
    static def +/ (int arg1, int arg2) {
        (arg1 + arg2) / 2
    }
}
```
should compile to:
```java
class Average{
    public static int operator_plusdivide(int arg1, int arg2) {
        return (arg1 + arg2) / 2;
    }
}
```
(or something similar)

Possible characters for a custom operator should include but not be limited to those already available: +,-,*,/,<,>,%,&,|,~,^,!, as well as some other currently unused characters: #,\\,: and ? (see #397 and #398 for already requested operators which could be implemented using this and extension methods).
The = character is also allowed except when used in some combinations, namely `=` (assign), `==` (equals), `===` (identical).
The . character is also allowed except when _not_ at the end of an operator (`+.` is allowed but `.+` is not). An exception to this rule are operators composed by multiple . characters: `..` and `....` are accepted representations of custom operators.

The name of the generated method should be `operator_` followed by the name of the characters involved in it. 
This means that the already-present << and >> operators (among others) can have two names: the current `operator_doublelessthan` and `operator_lessthanlessthan`, in which case the former should be used and kept for backwards compatibility.

**Comment by szarnekow** [comment]
We don't have plans to introduce a flexibility like this. Such a feature was discussed in the past and rejected because the complexity to implement it correctly outweighs the benefit. Especially the operator precedences and associativity of esoteric operators is a hard problem. For these, there usually is no well defined standard and whatever default we may come up with, it would potentially not meet the expectation. On top of that, the parser would become more complex implementation wise and runtime wise.

**Comment by szarnekow** [comment]
Marked as won't fix.
