### ISSUE TITLE
Dose xtend support default parameters and coalesce "??" operator ? 

### ISSUE THREAD

**Issue by LucaGabi** [eclipse/xtext-xtend#710]
Hi,

   Is the project still developing ? Dose it support default parameters and coalesce "??" operator ? 

Thanks.

**Comment by cdietrich** [comment]
There is no default params.
Since we don’t have arbitrary consider true semantic I assume the Elvis ?: does what you mean my coalesce 

The are no plans to have 1000s of features in Lang as eg C# has. We plan to introduce new things but our time is very limited an the work To ne spent in Xtext is more valuable from we currently see by users

**Comment by kthoms** [comment]
We are still developing Xtend very actively. We just do not work on new language features ATM. The language itself is fine for its purpose and as Christian said it is not the purpose to support all operators that may be known from other languages, as long as there are short and rather convenient ways to implement use cases with Xtend differently.

Since this is a question and "no" is the short answer, I'll close this issue. And no, there is no concrete schedule working on that now. If you or someone else wants to contribute that, we would happily receive a PR and review that.
