### ISSUE TITLE
Better code generation for dispatch functions with Void and Object

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-xtend#730]
When you use a dispatch with a `Void` argument, the generated code checks if the argument is `null`.

When you use a dispatch with an `Object` argument, the generated code checks if the argument is not `null`.

If you use them as a combination both will happen, however it will always be known that the argument is not null.

For example, the following Xtend:
```
package com.test.pkg

class Test {
	def dispatch void doThing(Void v) {}
	def dispatch void doThing(Object o) {}
}
```

Generates the following Java:
```
package com.test.pkg;

import java.util.Arrays;

@SuppressWarnings("all")
public class Test {
  protected void _doThing(final Void v) {
  }
  
  protected void _doThing(final Object o) {
  }
  
  public void doThing(final Object v) {
    if (v == null) {
      _doThing((Void)null);
      return;
    // v is known to be not null here making the else if and else useless, there should just be an else
    } else if (v != null) {
      _doThing(v);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(v).toString());
    }
  }
}
```

**Comment by miklossy** [comment]
See also https://github.com/eclipse/xtext-xtend/issues/174

**Comment by ArneDeutsch** [comment]
Investigated this for quite some time without coming to a working solution. A fix would be needed in `DispatchMethodCompileStrategy`.
Issues that make the issue complicated:
- One `if` is generated for every method. Exact content of each `if` statement is calculated for each one seperately. One would need to go through this list of methods one extra round and compute if generation is necessary in each case. This would probably make the generation process much slower. Because type information is needed for the process.
- Case is simple only for methods with exactly one parameter. It exists for multiple parameters as well and would be very hard to solve in general case. Example:

```
class Test {
	def dispatch void doThing(Object v, Object v1) {}
	def dispatch void doThing(Void v, Object v1) {}
	def dispatch void doThing(Object v, Void v1) {}
	def dispatch void doThing(Void v, Void v1) {}
}
```
```
  public void doThing(final Object v, final Object v1) {
    if (v == null
         && v1 == null) {
      _doThing((Void)null, (Void)null);
      return;
    } else if (v == null
         && v1 != null) {
      _doThing((Void)null, v1);
      return;
    } else if (v != null
         && v1 == null) {
      _doThing(v, (Void)null);
      return;
    } else if (v != null
         && v1 != null) {
      _doThing(v, v1);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(v, v1).toString());
    }
  }
```
I think it is probably not a good idea to slow down the compilation process just to detect the unnecessary code and avoid the warning. It one could find a solution that does not need the preprocessing it might be done, but I do not see how to do it. Maybe the type information in the preprocessing have to be cached then for the second round ...

**Comment by ArneDeutsch** [comment]
Just in case someone sometimes liek to work on this ... there is `DispatchCompilerTest.xtend`. A (first) suitable test would look like this:

```
@Test
def testVoidAndObject() {
	assertCompilesTo('''
		class Test {
			def dispatch void doThing(Void v) {}
			def dispatch void doThing(Object o) {}
		}
	''', '''
		import java.util.Arrays;
		
		@SuppressWarnings("all")
		public class Test {
		  protected void _doThing(final Void v) {
		  }
		  
		  protected void _doThing(final Object o) {
		  }
		  
		  public void doThing(final Object v) {
		    if (v == null) {
		      _doThing((Void)null);
		      return;
		    } else {
		      _doThing(v);
		      return;
		    }
		  }
		}
	''')
}
```

**Comment by ArneDeutsch** [comment]
Done.

**Comment by cdietrich** [comment]
thx Arne
