### ISSUE TITLE
Format compiled Java code

### ISSUE THREAD

**Issue by ivaniesta14** [eclipse/xtext-xtend#936]
When compiling to Java code there should be an option to format that code automatically after building, as the compiled code might be hard to debug in some cases (really long lines, variables/arguments interleaved with casts/explicit type arguments...).

**Comment by szarnekow** [comment]
The idea sounds intriguing, but I doubt that this is feasible. In order to inject the proper source maps into the classes, we need to know which Xtend expression / method was compiled to which offset in the Java source code. So whatever formatting is used as a postprocessing, it must update these mappings, too. 

What could work though, is to enhance the Xtend compiler to output prettier code right from the start.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
